// Dev server: builds once, serves docs/, then rebuilds and refreshes the
// browser whenever a file under src/, docs/, or scripts/ changes.
import { createServer } from 'node:http';
import { readFileSync, statSync, readdirSync, existsSync, watch } from 'node:fs';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, extname, sep } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = join(root, 'docs');
const port = Number(process.env.PORT) || 4000;

const WATCH_TARGETS = ['src', 'docs', 'scripts'];
const IGNORE_DIRS = new Set(['dist', 'node_modules', '.git']);
// Generated by the build itself (see scripts/gen-tokens.mjs) — watching it
// would make every build retrigger another build.
const IGNORE_FILES = new Set([join(root, 'src/css/tokens.css')]);

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

const LIVERELOAD_SNIPPET = `
<script>
(function () {
  const es = new EventSource('/__fw-livereload');
  es.onmessage = () => location.reload();
})();
</script>`;

// --- live reload clients ---
const clients = new Set();
function broadcastReload() {
  for (const res of clients) res.write('data: reload\n\n');
}

// --- build orchestration ---
let building = false;
let rebuildPending = false;
let serverStarted = false;

function runBuild() {
  if (building) {
    rebuildPending = true;
    return;
  }
  building = true;
  console.log('[dev] building...');
  const npmCmd = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const proc = spawn(npmCmd, ['run', 'build'], { cwd: root, stdio: 'inherit' });
  proc.on('exit', (code) => {
    building = false;
    if (code === 0) {
      console.log('[dev] build complete');
      if (serverStarted) broadcastReload();
    } else {
      console.error(`[dev] build failed (exit code ${code})`);
    }
    if (!serverStarted) {
      serverStarted = true;
      startWatchers();
      startServer();
    }
    if (rebuildPending) {
      rebuildPending = false;
      runBuild();
    }
  });
}

function debounce(fn, ms) {
  let timer;
  return () => {
    clearTimeout(timer);
    timer = setTimeout(fn, ms);
  };
}

const scheduleRebuild = debounce(runBuild, 150);

// --- recursive directory watching (portable: no reliance on fs.watch's
// platform-limited `recursive` option) ---
function watchDir(dir) {
  if (!existsSync(dir)) return;

  let watcher;
  try {
    watcher = watch(dir, (_event, filename) => {
      if (!filename) {
        scheduleRebuild();
        return;
      }
      // On macOS, fs.watch's underlying FSEvents backend reports changes for
      // the whole subtree even for a single non-recursive watch() call, so
      // `filename` here can be a nested path like 'dist/fernwell.css'. Skip
      // anything under an ignored directory at any depth.
      const segments = filename.split(sep);
      if (segments.some((s) => IGNORE_DIRS.has(s))) return;

      const full = join(dir, filename);
      if (IGNORE_FILES.has(full)) return;
      scheduleRebuild();
      if (existsSync(full) && statSync(full).isDirectory() && !IGNORE_DIRS.has(filename)) {
        watchDir(full);
      }
    });
  } catch {
    return;
  }
  watcher.on('error', () => watcher.close());

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory() && !IGNORE_DIRS.has(entry.name)) {
      watchDir(join(dir, entry.name));
    }
  }
}

function startWatchers() {
  for (const target of WATCH_TARGETS) {
    watchDir(join(root, target));
  }
  console.log(`[dev] watching ${WATCH_TARGETS.join(', ')} for changes`);
}

// --- static file server ---
function resolveSafePath(requestPath) {
  const decoded = decodeURIComponent(requestPath.split('?')[0]);
  const resolved = join(docsDir, decoded);
  if (resolved !== docsDir && !resolved.startsWith(docsDir + sep)) return null;
  return resolved;
}

function startServer() {
  const server = createServer((req, res) => {
    if (req.url === '/__fw-livereload') {
      res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        Connection: 'keep-alive',
      });
      res.write('\n');
      clients.add(res);
      req.on('close', () => clients.delete(res));
      return;
    }

    let filePath = resolveSafePath(req.url === '/' ? '/index.html' : req.url);
    if (!filePath) {
      res.writeHead(400);
      res.end('Bad request');
      return;
    }

    try {
      if (statSync(filePath).isDirectory()) filePath = join(filePath, 'index.html');
      const ext = extname(filePath);
      const contentType = MIME[ext] || 'application/octet-stream';
      let body = readFileSync(filePath);
      if (ext === '.html') {
        body = Buffer.from(body.toString('utf8').replace('</body>', `${LIVERELOAD_SNIPPET}\n</body>`));
      }
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(body);
    } catch {
      res.writeHead(404);
      res.end('Not found');
    }
  });

  server.listen(port, () => {
    console.log(`[dev] serving docs/ at http://localhost:${port}`);
  });
}

runBuild();
